### ISSUE TITLE
co to jest

### ISSUE THREAD

**Issue by inzynierr** [warsztatt/height-calculator-tool#1]
????

**Comment by warsztatt** [comment]
Witam inzynier, jest to zaawansowny program do sprawdzania wzrostu

**Comment by Memexurer** [comment]
![cock](https://user-images.githubusercontent.com/34003944/128688701-175d0e80-5a66-4105-8c4f-8c7aa78af7b7.jpg)

**Comment by warsztatt** [comment]
Accept

**Comment by inzynierr** [comment]
rozumiem
